// Copyright 2021 Gamergenic.  See full copyright notice in Spice.h.
// Author: chucknoble@gamergenic.com | https://www.gamergenic.com
// 
// Implementation of:
// "Adding Third-Party Libraries to Unreal Engine : NASA's SPICE Toolkit"
// https://gamedevtricks.com/post/third-party-libs-1/

#include "K2Node_bodvcd.h"
#include "K2Node_OperationNOutput.h"
#include "K2Utilities.h"
#include "SpiceK2.h"

#include "EdGraphSchema_K2.h"

#include "KismetCompiler.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "K2Node_CallFunction.h"


using namespace ENodeTitleType;


#define LOCTEXT_NAMESPACE "K2Node_bodvcd"


UK2Node_bodvcd::UK2Node_bodvcd()
{
    OperationsMap = TMap<FName, FK2OperationNOutput>();

    auto op = DoubleOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = ArrayDoubleOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = SDimensionlessVectorOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = SMassConstantOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = SDistanceOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = SDegreesOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = SDistanceVectorOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = SVelocityVectorOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);
    op = WildcardOp(); op.FullName = op.ShortName.ToString() + "\nReturn value from the kernel pool"; OperationsMap.Emplace(op.ShortName, op);

    CurrentOperation = op;
}


FText UK2Node_bodvcd::GetNodeTitle(Type TitleType) const
{
    switch (TitleType)
    {
    case FullTitle:
        /** The full title, may be multiple lines. */
        return FText::FromString(CurrentOperation.FullName);
    case ListView:
        /** More concise, single line title. */
        return LOCTEXT("ListViewTitle", "bodvcd - fetch value from kernel pool");
    case MenuTitle:
        /** Menu Title for context menus to be displayed in context menus referencing the node. */
        return LOCTEXT("MenuTitle", "bodvcd");
    }

    return LOCTEXT("ShortTitle", "bodvcd");
}


FText UK2Node_bodvcd::GetMenuCategory() const
{
    return LOCTEXT("Category", "Spice|Api|Kernel");
}


FText UK2Node_bodvcd::GetKeywords() const
{
    return LOCTEXT("Keywords", "CONSTANTS");
}


FText UK2Node_bodvcd::GetTooltipText() const
{
    return LOCTEXT("Tooltip", "Fetch from the kernel pool the double precision values of an item associated with a body");
}



void UK2Node_bodvcd::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
    RegisterAction(ActionRegistrar, GetClass());
}

void UK2Node_bodvcd::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
    Super::NotifyPinConnectionListChanged(Pin);

    if (Pin->LinkedTo.Num() != 1)
    {
        CurrentOperation = WildcardOp();
        const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();
        K2Schema->ForceVisualizationCacheClear();
    }
}



void UK2Node_bodvcd::AllocateDefaultPins()
{
    Super::AllocateDefaultPins();

    const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();

    // Inputs - Body/Item
    UEdGraphPin* bodyPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, body_Field);
    K2Schema->SetPinAutogeneratedDefaultValue(bodyPin, body_Value);
    bodyPin->PinToolTip = TEXT("Body name");
    bodyPin->DefaultValue = FString::FromInt(body_DefaultValue);

    UEdGraphPin * itemPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, item_Field);
    K2Schema->SetPinAutogeneratedDefaultValue(itemPin, item_Value);
    itemPin->PinToolTip = TEXT("Item for which values are desired. (\"RADII\", \"NUT_PREC_ANGLES\", etc.)");
    itemPin->DefaultValue = item_DefaultValue.ToString();
}


void UK2Node_bodvcd::ReconstructNode()
{
    Super::ReconstructNode();

    if (returnValuePin()->LinkedTo.Num() != 1)
    {
        CurrentOperation = WildcardOp();
    }
}

void UK2Node_bodvcd::ExpandOperationNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, UK2Node* operationNode)
{
    auto Schema = Cast< UEdGraphSchema_K2 >(GetSchema());

    // Now the body and item pins...
    auto thisBody = bodyPin();   auto thatBody = operationNode->FindPinChecked(body_Field);
    auto thisItem = itemPin();   auto thatItem = operationNode->FindPinChecked(item_Field);

    MovePinLinksOrCopyDefaults(CompilerContext, thisBody, thatBody);
    MovePinLinksOrCopyDefaults(CompilerContext, thisItem, thatItem);
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::WildcardOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd"), FName("bodvcd_double_K2"), FK2Type::Wildcard());
    v.FullName = v.ShortName.ToString() + "\nReturn value from the kernel pool";
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::DoubleOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd Double"), FName("bodvcd_double_K2"), FK2Type::Double());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::ArrayDoubleOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd Array(Double)"), FName("bodvcd_array_K2"), FK2Type::DoubleArray());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::SDimensionlessVectorOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd SDimensionlessVector"), FName("bodvcd_vector_K2"), FK2Type::SDimensionlessVector());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::SMassConstantOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd SMassConstant"), FName("bodvcd_double_K2"), FK2Conversion::DoubleToSMassConstant());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::SDistanceOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd SDistance"), FName("bodvcd_double_K2"), FK2Conversion::DoubleToSDistance());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::SDegreesOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd SAngle(Degrees)"), FName("bodvcd_double_K2"), FK2Conversion::DegreesToSAngle());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::SDistanceVectorOp()
{

    static auto v = FK2OperationNOutput(FName("bodvcd SDistanceVector"), FName("bodvcd_vector_K2"), FK2Conversion::SDimensionlessVectorToSDistanceVector());
    return v;
}

SPICEUNCOOKED_API FK2OperationNOutput UK2Node_bodvcd::SVelocityVectorOp()
{
    static auto v = FK2OperationNOutput(FName("bodvcd SVelocityVector"), FName("bodvcd_vector_K2"), FK2Conversion::SDimensionlessVectorToSVelocityVector());
    return v;
}



#undef LOCTEXT_NAMESPACE